server:
  port: 8888

spring:
  application:
    name: configserver

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Zhoutao822/springcloud.git
          search-paths: config
          username: zhoutao822
          password: 995122@ice
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true